using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Typhon.Generators;

/// <summary>
/// Incremental source generator that emits the boilerplate half of every typed-event ref struct in
/// <c>Typhon.Engine.Profiler.Events</c>. Decorate a partial ref struct with
/// <c>[TraceEvent(TraceEventKind.X)]</c> and (for events with optional fields) <c>Codec = typeof(...)</c>;
/// the generator emits the <c>: ITraceEventEncoder</c> interface implementation, the static <c>Kind</c>
/// property, the <c>Header</c> field, the public property + mask-flipping setter for each
/// <c>[Optional]</c>-tagged private backing field, and the <c>Dispose</c> method that publishes through
/// <c>TyphonEvent.PublishEvent</c>. The user retains <c>ComputeSize</c> and <c>EncodeTo</c> in their own
/// partial half because the codec call signature is per-kind and not meaningfully template-able until
/// Phase 3 (#294).
/// </summary>
[Generator(LanguageNames.CSharp)]
public class TraceEventGenerator : IIncrementalGenerator
{
    private const string TraceEventAttributeFqn = "Typhon.Engine.Profiler.TraceEventAttribute";
    private const string OptionalAttributeFqn = "Typhon.Engine.Profiler.OptionalAttribute";
    private const string BeginParamAttributeFqn = "Typhon.Engine.Profiler.BeginParamAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Synthesize the [TraceEvent] / [Optional] attributes so user code can reference them without
        // shipping an extra annotations DLL. The post-init output is added to the compilation before
        // user code is processed, so [TraceEvent(TraceEventKind.X)] resolves immediately.
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("TraceEventAttributes.g.cs",
@"// <auto-generated/>
#nullable disable
using System;
using Typhon.Profiler;

namespace Typhon.Engine.Profiler
{
    /// <summary>
    /// Marks a partial ref struct as a typed event for the Typhon profiler. The generator emits the
    /// header field, kind constant, optional-property accessors, and Dispose method as a partial half;
    /// the user retains ComputeSize and EncodeTo.
    /// </summary>
    [AttributeUsage(AttributeTargets.Struct, AllowMultiple = false, Inherited = false)]
    public sealed class TraceEventAttribute : Attribute
    {
        public TraceEventAttribute(TraceEventKind kind) { Kind = kind; }
        public TraceEventKind Kind { get; }
        /// <summary>Codec class containing the OptX mask constants. Required only if any field is [Optional].</summary>
        public Type Codec { get; set; }
        /// <summary>Override for the generated Begin factory name. Defaults to ""Begin"" + Kind name.</summary>
        public string FactoryName { get; set; }
        /// <summary>Set to false to skip generating a Begin factory (for kinds emitted via custom code).</summary>
        public bool GenerateFactory { get; set; } = true;
        /// <summary>
        /// When true, the generator emits ComputeSize and EncodeTo directly, bypassing the per-kind codec
        /// Encode method. Use only for events whose wire layout is the standard span shape:
        /// header + (optional trace context) + required payload fields in declaration order +
        /// (optMask byte if any [Optional]) + optional fields in declaration order. Events with
        /// kind-specific layouts (TransactionCommitComponent's componentTypeId slot, TransactionPersist's
        /// walLsn-in-componentTypeId-slot, variable-length payloads) must keep EmitEncoder = false and
        /// retain their hand-written codec call.
        /// </summary>
        public bool EmitEncoder { get; set; }
    }

    /// <summary>
    /// Marks a private backing field as carrying an optional payload value. The generator emits a public
    /// property (PascalCase of the field name without the leading underscore) whose setter assigns the
    /// backing field and flips the matching OptX bit in _optMask.
    /// </summary>
    [AttributeUsage(AttributeTargets.Field, AllowMultiple = false, Inherited = false)]
    public sealed class OptionalAttribute : Attribute
    {
        /// <summary>Override for the mask constant name. Defaults to ""Opt"" + PascalCase(field name).</summary>
        public string MaskConstant { get; set; }
        /// <summary>Override for the public property name. Defaults to PascalCase(field name without underscore).</summary>
        public string PropertyName { get; set; }
    }

    /// <summary>
    /// Marks a public payload field as a Begin-factory parameter. Fields without this attribute are not
    /// factory params (they are filled later by the caller before Dispose runs).
    /// </summary>
    [AttributeUsage(AttributeTargets.Field, AllowMultiple = false, Inherited = false)]
    public sealed class BeginParamAttribute : Attribute
    {
        /// <summary>
        /// Overrides the factory parameter type. Defaults to the field's type. When set, the generator
        /// emits an explicit cast in the factory body: Field = (FieldType)param.
        /// </summary>
        public string ParamType { get; set; }
    }
}
");
        });

        var pipeline = context.SyntaxProvider.ForAttributeWithMetadataName(
            fullyQualifiedMetadataName: TraceEventAttributeFqn,
            predicate: static (node, _) => node is StructDeclarationSyntax,
            transform: static (ctx, ct) => Transform(ctx, ct)
        );

        context.RegisterSourceOutput(pipeline, static (spc, model) =>
        {
            if (model == null)
            {
                return;
            }
            spc.AddSource($"{model.StructName}.g.cs", Emit(model));
        });
    }

    // ═══════════════════════════════════════════════════════════════════════
    // Transform: syntax + semantic model → TraceEventModel
    // ═══════════════════════════════════════════════════════════════════════

    private static TraceEventModel Transform(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        var structDecl = (StructDeclarationSyntax)ctx.TargetNode;
        var symbol = (INamedTypeSymbol)ctx.TargetSymbol;

        // Must be partial.
        bool isPartial = false;
        foreach (var modifier in structDecl.Modifiers)
        {
            if (modifier.Text == "partial")
            {
                isPartial = true;
                break;
            }
        }
        if (!isPartial)
        {
            return null;
        }

        // Pull TraceEvent attribute data.
        var attrData = ctx.Attributes.FirstOrDefault();
        if (attrData == null || attrData.ConstructorArguments.Length < 1)
        {
            return null;
        }

        // Kind enum field name: the constructor arg is a TypedConstant whose Value is the int enum value.
        // We want the literal field name (e.g. "BTreeInsert") to emit as TraceEventKind.BTreeInsert.
        string kindName = ResolveKindName(attrData.ConstructorArguments[0]);
        if (kindName == null)
        {
            return null;
        }

        // Codec = typeof(X)  (named arg, optional)
        string codecFqn = null;
        string factoryName = null;
        bool generateFactory = true;
        bool emitEncoder = false;
        foreach (var named in attrData.NamedArguments)
        {
            if (named.Key == "Codec" && named.Value.Value is INamedTypeSymbol codecSymbol)
            {
                codecFqn = codecSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            }
            else if (named.Key == "FactoryName" && named.Value.Value is string fn)
            {
                factoryName = fn;
            }
            else if (named.Key == "GenerateFactory" && named.Value.Value is bool gf)
            {
                generateFactory = gf;
            }
            else if (named.Key == "EmitEncoder" && named.Value.Value is bool ee)
            {
                emitEncoder = ee;
            }
        }

        // Walk fields, pick out the [Optional]-tagged private ones and [BeginParam]-tagged public ones.
        var optionals = new List<OptionalFieldModel>();
        var beginParams = new List<BeginParamModel>();
        foreach (var member in symbol.GetMembers())
        {
            if (!(member is IFieldSymbol field))
            {
                continue;
            }

            AttributeData optAttr = null;
            AttributeData beginParamAttr = null;
            foreach (var a in field.GetAttributes())
            {
                var fqn = a.AttributeClass?.ToDisplayString();
                if (fqn == OptionalAttributeFqn)
                {
                    optAttr = a;
                }
                else if (fqn == BeginParamAttributeFqn)
                {
                    beginParamAttr = a;
                }
            }

            if (optAttr != null)
            {
                string fieldName = field.Name;
                string typeName = field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                // For enum fields, the wire representation is the underlying integer type. We store the
                // underlying type as `wireTypeName` and emit a cast on write.
                string wireTypeName = typeName;
                bool isEnum = false;
                if (field.Type is INamedTypeSymbol et && et.TypeKind == TypeKind.Enum && et.EnumUnderlyingType != null)
                {
                    wireTypeName = et.EnumUnderlyingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    isEnum = true;
                }

                string propertyName = null;
                string maskConstant = null;
                foreach (var named in optAttr.NamedArguments)
                {
                    if (named.Key == "PropertyName" && named.Value.Value is string pn)
                    {
                        propertyName = pn;
                    }
                    else if (named.Key == "MaskConstant" && named.Value.Value is string mc)
                    {
                        maskConstant = mc;
                    }
                }
                propertyName ??= DerivePropertyName(fieldName);
                maskConstant ??= "Opt" + propertyName;

                optionals.Add(new OptionalFieldModel(fieldName, typeName, wireTypeName, isEnum, propertyName, maskConstant));
            }

            if (beginParamAttr != null)
            {
                string fieldName = field.Name;
                string fieldTypeName = field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                string paramTypeOverride = null;
                foreach (var named in beginParamAttr.NamedArguments)
                {
                    if (named.Key == "ParamType" && named.Value.Value is string pt)
                    {
                        paramTypeOverride = pt;
                    }
                }
                string paramName = char.ToLowerInvariant(fieldName[0]) + fieldName.Substring(1);
                beginParams.Add(new BeginParamModel(fieldName, fieldTypeName, paramName, paramTypeOverride));
            }
        }

        // If there are optionals, the codec must be specified — that's where the mask constants live.
        if (optionals.Count > 0 && codecFqn == null)
        {
            return null;
        }

        // Walk public payload fields in declaration order — used when EmitEncoder = true. Walk the syntax
        // tree (not the symbol member list) because partial-struct symbols don't preserve syntactic field
        // order between halves.
        var payloadFields = new List<PayloadFieldModel>();
        foreach (var member in structDecl.Members)
        {
            if (!(member is FieldDeclarationSyntax fdecl))
            {
                continue;
            }
            // Must be public.
            bool isPublic = false;
            foreach (var mod in fdecl.Modifiers)
            {
                if (mod.Text == "public") { isPublic = true; break; }
            }
            if (!isPublic)
            {
                continue;
            }
            // Skip if it has any [Optional] / [BeginParam] (covered in those collections separately).
            // Actually we DO include [BeginParam] fields in payload — they ARE payload, just also factory params.
            foreach (var v in fdecl.Declaration.Variables)
            {
                string fieldName = v.Identifier.Text;
                if (fieldName == "Header") continue;
                var typeSymbol = ctx.SemanticModel.GetTypeInfo(fdecl.Declaration.Type).Type;
                if (typeSymbol == null) continue;
                string typeName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                string wireTypeName = typeName;
                bool isEnum = false;
                if (typeSymbol is INamedTypeSymbol ents && ents.TypeKind == TypeKind.Enum && ents.EnumUnderlyingType != null)
                {
                    wireTypeName = ents.EnumUnderlyingType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    isEnum = true;
                }
                payloadFields.Add(new PayloadFieldModel(fieldName, typeName, wireTypeName, isEnum));
            }
        }

        return new TraceEventModel(
            ns: symbol.ContainingNamespace?.ToDisplayString() ?? "",
            structName: symbol.Name,
            kindName: kindName,
            codecFqn: codecFqn,
            optionals: optionals.ToArray(),
            beginParams: beginParams.ToArray(),
            payloadFields: payloadFields.ToArray(),
            factoryName: factoryName ?? ("Begin" + kindName),
            generateFactory: generateFactory,
            emitEncoder: emitEncoder
        );
    }

    private static string ResolveKindName(TypedConstant arg)
    {
        if (!(arg.Type is INamedTypeSymbol enumType) || enumType.TypeKind != TypeKind.Enum || arg.Value == null)
        {
            return null;
        }
        // Convert the boxed enum value to long for cross-underlying-type comparison (byte/short/int/long all OK).
        long ordinal = System.Convert.ToInt64(arg.Value);
        foreach (var m in enumType.GetMembers())
        {
            if (m is IFieldSymbol fs && fs.IsConst && fs.HasConstantValue && fs.ConstantValue != null
                && System.Convert.ToInt64(fs.ConstantValue) == ordinal)
            {
                return fs.Name;
            }
        }
        return null;
    }

    /// <summary>Wire size in bytes for a primitive type. Returns -1 if unknown.</summary>
    private static int WireSize(string typeFqn)
    {
        // Strip global:: prefix and namespace if present — we just need the leaf name.
        int idx = typeFqn.LastIndexOf('.');
        string leaf = idx >= 0 ? typeFqn.Substring(idx + 1) : typeFqn;
        switch (leaf)
        {
            case "byte":
            case "Byte":
            case "sbyte":
            case "SByte":
            case "bool":
            case "Boolean":
                return 1;
            case "short":
            case "Int16":
            case "ushort":
            case "UInt16":
                return 2;
            case "int":
            case "Int32":
            case "uint":
            case "UInt32":
            case "float":
            case "Single":
                return 4;
            case "long":
            case "Int64":
            case "ulong":
            case "UInt64":
            case "double":
            case "Double":
                return 8;
            default:
                return -1;
        }
    }

    /// <summary>Emit the byte-write call for a single field given its type and the cursor expression.</summary>
    private static string WriteCall(string typeFqn, string spanExpr, string valueExpr)
    {
        int idx = typeFqn.LastIndexOf('.');
        string leaf = idx >= 0 ? typeFqn.Substring(idx + 1) : typeFqn;
        switch (leaf)
        {
            case "byte":
            case "Byte":
                return $"{spanExpr}[0] = {valueExpr};";
            case "sbyte":
            case "SByte":
                return $"{spanExpr}[0] = (byte){valueExpr};";
            case "bool":
            case "Boolean":
                return $"{spanExpr}[0] = {valueExpr} ? (byte)1 : (byte)0;";
            case "short":
            case "Int16":
                return $"global::System.Buffers.Binary.BinaryPrimitives.WriteInt16LittleEndian({spanExpr}, {valueExpr});";
            case "ushort":
            case "UInt16":
                return $"global::System.Buffers.Binary.BinaryPrimitives.WriteUInt16LittleEndian({spanExpr}, {valueExpr});";
            case "int":
            case "Int32":
                return $"global::System.Buffers.Binary.BinaryPrimitives.WriteInt32LittleEndian({spanExpr}, {valueExpr});";
            case "uint":
            case "UInt32":
                return $"global::System.Buffers.Binary.BinaryPrimitives.WriteUInt32LittleEndian({spanExpr}, {valueExpr});";
            case "float":
            case "Single":
                return $"global::System.Buffers.Binary.BinaryPrimitives.WriteSingleLittleEndian({spanExpr}, {valueExpr});";
            case "long":
            case "Int64":
                return $"global::System.Buffers.Binary.BinaryPrimitives.WriteInt64LittleEndian({spanExpr}, {valueExpr});";
            case "ulong":
            case "UInt64":
                return $"global::System.Buffers.Binary.BinaryPrimitives.WriteUInt64LittleEndian({spanExpr}, {valueExpr});";
            case "double":
            case "Double":
                return $"global::System.Buffers.Binary.BinaryPrimitives.WriteDoubleLittleEndian({spanExpr}, {valueExpr});";
            default:
                // Hard fail at compile time. A silent `// UNKNOWN` comment in the generated EncodeTo would let
                // the build succeed and silently corrupt wire bytes for the unsupported field. The #error stops
                // the build with a precise, actionable message pointing at the offending type and field.
                return $"#error TraceEventGenerator: unsupported wire type '{typeFqn}' for value '{valueExpr}'. Add a primitive backing field, mark the kind as a [CustomEncoder] escape-hatch, or extend WireSize/WriteCall in the generator.";
        }
    }

    private static void EmitEncoderMethods(StringBuilder sb, string indent, TraceEventModel model)
    {
        const string TR = "global::Typhon.Profiler.TraceRecordHeader";

        // Required-payload fixed size = sum of WireSize for each non-Optional public field.
        int requiredPayloadSize = 0;
        foreach (var p in model.PayloadFields)
        {
            int sz = WireSize(p.WireTypeFqn);
            if (sz < 0)
            {
                // Hard-fail the build. Silent fallthrough would write a partial encoder that produces wrong wire bytes.
                sb.Append(indent).Append("    #error TraceEventGenerator: unsupported wire type '").Append(p.WireTypeFqn)
                    .Append("' for payload field '").Append(p.FieldName).Append("' on ").Append(model.StructName)
                    .AppendLine(". Use a primitive type, mark the kind as a [CustomEncoder] escape-hatch, or extend WireSize/WriteCall in the generator.");
                return;
            }
            requiredPayloadSize += sz;
        }

        foreach (var opt in model.Optionals)
        {
            if (WireSize(opt.WireTypeFqn) < 0)
            {
                sb.Append(indent).Append("    #error TraceEventGenerator: unsupported wire type '").Append(opt.WireTypeFqn)
                    .Append("' for optional field '").Append(opt.FieldName).Append("' on ").Append(model.StructName)
                    .AppendLine(". Use a primitive type, mark the kind as a [CustomEncoder] escape-hatch, or extend WireSize/WriteCall in the generator.");
                return;
            }
        }

        bool hasOptionals = model.Optionals.Length > 0;
        int optMaskSize = hasOptionals ? 1 : 0;

        // ── ComputeSize ──
        sb.AppendLine();
        sb.Append(indent).AppendLine("    public readonly int ComputeSize()");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).AppendLine($"        var hasTraceContext = Header.TraceIdHi != 0 || Header.TraceIdLo != 0;");
        sb.Append(indent).Append("        var size = ").Append(TR).AppendLine(".SpanHeaderSize(hasTraceContext);");
        if (requiredPayloadSize > 0)
        {
            sb.Append(indent).Append("        size += ").Append(requiredPayloadSize).AppendLine(";");
        }
        if (hasOptionals)
        {
            sb.Append(indent).AppendLine("        size += 1; // optMask byte");
            foreach (var opt in model.Optionals)
            {
                int optSz = WireSize(opt.WireTypeFqn);
                sb.Append(indent).Append("        if ((_optMask & ").Append(model.CodecFqn).Append('.').Append(opt.MaskConstant).Append(") != 0) size += ").Append(optSz).AppendLine(";");
            }
        }
        sb.Append(indent).AppendLine("        return size;");
        sb.Append(indent).AppendLine("    }");

        // ── EncodeTo ──
        sb.AppendLine();
        sb.Append(indent).AppendLine("    public readonly void EncodeTo(global::System.Span<byte> destination, long endTimestamp, out int bytesWritten)");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).AppendLine("        var hasTraceContext = Header.TraceIdHi != 0 || Header.TraceIdLo != 0;");
        sb.Append(indent).AppendLine("        var size = ComputeSize();");
        sb.Append(indent).Append("        ").Append(TR).Append(".WriteCommonHeader(destination, (ushort)size, TraceEventKind.")
            .Append(model.KindName).AppendLine(", Header.ThreadSlot, Header.StartTimestamp);");
        sb.Append(indent).Append("        var spanFlags = hasTraceContext ? ").Append(TR).AppendLine(".SpanFlagsHasTraceContext : (byte)0;");
        sb.Append(indent).Append("        ").Append(TR).Append(".WriteSpanHeaderExtension(destination[").Append(TR).AppendLine(".CommonHeaderSize..],");
        sb.Append(indent).AppendLine("            endTimestamp - Header.StartTimestamp, Header.SpanId, Header.ParentSpanId, spanFlags);");
        sb.Append(indent).AppendLine("        if (hasTraceContext)");
        sb.Append(indent).AppendLine("        {");
        sb.Append(indent).Append("            ").Append(TR).Append(".WriteTraceContext(destination[").Append(TR).AppendLine(".MinSpanHeaderSize..], Header.TraceIdHi, Header.TraceIdLo);");
        sb.Append(indent).AppendLine("        }");

        // Payload writes (after header).
        if (requiredPayloadSize > 0 || hasOptionals)
        {
            sb.Append(indent).Append("        var headerSize = ").Append(TR).AppendLine(".SpanHeaderSize(hasTraceContext);");
            sb.Append(indent).AppendLine("        var payload = destination[headerSize..];");
            int cursor = 0;
            foreach (var p in model.PayloadFields)
            {
                int sz = WireSize(p.WireTypeFqn);
                string spanExpr = cursor == 0 ? "payload" : $"payload[{cursor}..]";
                string valueExpr = p.IsEnum ? $"({p.WireTypeFqn}){p.FieldName}" : p.FieldName;
                sb.Append(indent).Append("        ").AppendLine(WriteCall(p.WireTypeFqn, spanExpr, valueExpr));
                cursor += sz;
            }
            if (hasOptionals)
            {
                string spanExpr = cursor == 0 ? "payload" : $"payload[{cursor}..]";
                sb.Append(indent).Append("        ").Append(spanExpr).AppendLine("[0] = _optMask;");
                cursor += 1;
                sb.Append(indent).Append("        var optCursor = ").Append(cursor).AppendLine(";");
                foreach (var opt in model.Optionals)
                {
                    int optSz = WireSize(opt.WireTypeFqn);
                    string valueExpr = opt.IsEnum ? $"({opt.WireTypeFqn}){opt.FieldName}" : opt.FieldName;
                    sb.Append(indent).Append("        if ((_optMask & ").Append(model.CodecFqn).Append('.').Append(opt.MaskConstant).AppendLine(") != 0)");
                    sb.Append(indent).AppendLine("        {");
                    sb.Append(indent).Append("            ").AppendLine(WriteCall(opt.WireTypeFqn, "payload[optCursor..]", valueExpr));
                    sb.Append(indent).Append("            optCursor += ").Append(optSz).AppendLine(";");
                    sb.Append(indent).AppendLine("        }");
                }
            }
        }

        sb.Append(indent).AppendLine("        bytesWritten = size;");
        sb.Append(indent).AppendLine("    }");
    }

    /// <summary>Convert "_componentCount" → "ComponentCount". Strips a single leading underscore.</summary>
    private static string DerivePropertyName(string fieldName)
    {
        if (fieldName.Length == 0)
        {
            return fieldName;
        }
        int start = fieldName[0] == '_' ? 1 : 0;
        if (start >= fieldName.Length)
        {
            return fieldName;
        }
        return char.ToUpperInvariant(fieldName[start]) + fieldName.Substring(start + 1);
    }

    // ═══════════════════════════════════════════════════════════════════════
    // Emit: TraceEventModel → source code
    // ═══════════════════════════════════════════════════════════════════════

    private static string Emit(TraceEventModel model)
    {
        var sb = new StringBuilder(2048);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable CS8019 // Unnecessary using directive");
        sb.AppendLine("using System;");
        sb.AppendLine("using Typhon.Profiler;");
        sb.AppendLine();

        bool hasNs = !string.IsNullOrEmpty(model.Namespace);
        if (hasNs)
        {
            sb.Append("namespace ").AppendLine(model.Namespace);
            sb.AppendLine("{");
        }

        var indent = hasNs ? "    " : "";
        sb.Append(indent).Append("public ref partial struct ").Append(model.StructName).AppendLine(" : ITraceEventEncoder");
        sb.Append(indent).AppendLine("{");

        // static byte Kind => (byte)TraceEventKind.X;
        sb.Append(indent).Append("    public static byte Kind => (byte)TraceEventKind.").Append(model.KindName).AppendLine(";");
        sb.AppendLine();

        // public TraceSpanHeader Header;
        sb.Append(indent).AppendLine("    public TraceSpanHeader Header;");
        sb.AppendLine();

        // private byte _optMask; (only if any optional)
        if (model.Optionals.Length > 0)
        {
            sb.Append(indent).AppendLine("    private byte _optMask;");
            sb.AppendLine();

            // Public property + mask-flipping setter per optional.
            foreach (var opt in model.Optionals)
            {
                sb.Append(indent).Append("    public ").Append(opt.TypeFqn).Append(' ').AppendLine(opt.PropertyName);
                sb.Append(indent).AppendLine("    {");
                sb.Append(indent).Append("        readonly get => ").Append(opt.FieldName).AppendLine(";");
                sb.Append(indent).Append("        set { ").Append(opt.FieldName).Append(" = value; _optMask |= ")
                    .Append(model.CodecFqn).Append('.').Append(opt.MaskConstant).AppendLine("; }");
                sb.Append(indent).AppendLine("    }");
                sb.AppendLine();
            }
        }

        // public void Dispose() => TyphonEvent.PublishEvent(ref this, Header.ThreadSlot, Header.PreviousSpanId, Header.SpanId);
        sb.Append(indent).AppendLine("    public void Dispose() => TyphonEvent.PublishEvent(ref this, Header.ThreadSlot, Header.PreviousSpanId, Header.SpanId);");

        // ComputeSize + EncodeTo (Phase 3) when EmitEncoder = true. The user partial omits these methods.
        if (model.EmitEncoder)
        {
            EmitEncoderMethods(sb, indent, model);
        }

        sb.Append(indent).AppendLine("}");

        // Begin factory emitted as a partial half of TyphonEvent (which itself is in this same namespace).
        if (model.GenerateFactory)
        {
            sb.AppendLine();
            sb.Append(indent).AppendLine("public static partial class TyphonEvent");
            sb.Append(indent).AppendLine("{");
            sb.Append(indent).AppendLine("    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]");
            sb.Append(indent).Append("    public static ").Append(model.StructName).Append(' ').Append(model.FactoryName).Append('(');
            for (int i = 0; i < model.BeginParams.Length; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append(model.BeginParams[i].ParamTypeFqn).Append(' ').Append(model.BeginParams[i].ParamName);
            }
            sb.AppendLine(")");
            sb.Append(indent).AppendLine("    {");
            sb.Append(indent).AppendLine("        if (!BeginPrologue(TraceEventKind." + model.KindName + ", out var slotIdx, out var startTs, out var spanId, out var parentSpanId,");
            sb.Append(indent).AppendLine("                           out var previousSpanId, out var traceIdHi, out var traceIdLo))");
            sb.Append(indent).AppendLine("        {");
            sb.Append(indent).AppendLine("            return default;");
            sb.Append(indent).AppendLine("        }");
            sb.Append(indent).Append("        return new ").Append(model.StructName).AppendLine();
            sb.Append(indent).AppendLine("        {");
            sb.Append(indent).AppendLine("            Header = MakeHeader(slotIdx, startTs, spanId, parentSpanId, previousSpanId, traceIdHi, traceIdLo),");
            foreach (var p in model.BeginParams)
            {
                sb.Append(indent).Append("            ").Append(p.FieldName).Append(" = ");
                if (p.NeedsCast)
                {
                    sb.Append('(').Append(p.FieldTypeFqn).Append(')');
                }
                sb.Append(p.ParamName).AppendLine(",");
            }
            sb.Append(indent).AppendLine("        };");
            sb.Append(indent).AppendLine("    }");
            sb.Append(indent).AppendLine("}");
        }

        if (hasNs)
        {
            sb.AppendLine("}");
        }
        return sb.ToString();
    }

    // ═══════════════════════════════════════════════════════════════════════
    // Models
    // ═══════════════════════════════════════════════════════════════════════

    private sealed class TraceEventModel
    {
        public TraceEventModel(string ns, string structName, string kindName, string codecFqn, OptionalFieldModel[] optionals,
            BeginParamModel[] beginParams, PayloadFieldModel[] payloadFields, string factoryName, bool generateFactory, bool emitEncoder)
        {
            Namespace = ns;
            StructName = structName;
            KindName = kindName;
            CodecFqn = codecFqn;
            Optionals = optionals;
            BeginParams = beginParams;
            PayloadFields = payloadFields;
            FactoryName = factoryName;
            GenerateFactory = generateFactory;
            EmitEncoder = emitEncoder;
        }
        public string Namespace { get; }
        public string StructName { get; }
        public string KindName { get; }
        public string CodecFqn { get; }
        public OptionalFieldModel[] Optionals { get; }
        public BeginParamModel[] BeginParams { get; }
        public PayloadFieldModel[] PayloadFields { get; }
        public string FactoryName { get; }
        public bool GenerateFactory { get; }
        public bool EmitEncoder { get; }
    }

    private sealed class PayloadFieldModel
    {
        public PayloadFieldModel(string fieldName, string typeFqn, string wireTypeFqn, bool isEnum)
        {
            FieldName = fieldName;
            TypeFqn = typeFqn;
            WireTypeFqn = wireTypeFqn;
            IsEnum = isEnum;
        }
        public string FieldName { get; }
        public string TypeFqn { get; }
        public string WireTypeFqn { get; }
        public bool IsEnum { get; }
    }

    private sealed class OptionalFieldModel
    {
        public OptionalFieldModel(string fieldName, string typeFqn, string wireTypeFqn, bool isEnum, string propertyName, string maskConstant)
        {
            FieldName = fieldName;
            TypeFqn = typeFqn;
            WireTypeFqn = wireTypeFqn;
            IsEnum = isEnum;
            PropertyName = propertyName;
            MaskConstant = maskConstant;
        }
        public string FieldName { get; }
        public string TypeFqn { get; }
        /// <summary>For enum fields, the underlying primitive type used for wire encoding (e.g. "byte"). Same as TypeFqn for non-enums.</summary>
        public string WireTypeFqn { get; }
        public bool IsEnum { get; }
        public string PropertyName { get; }
        public string MaskConstant { get; }
    }

    private sealed class BeginParamModel
    {
        public BeginParamModel(string fieldName, string fieldTypeFqn, string paramName, string paramTypeOverride)
        {
            FieldName = fieldName;
            FieldTypeFqn = fieldTypeFqn;
            ParamName = paramName;
            ParamTypeOverride = paramTypeOverride;
        }
        public string FieldName { get; }
        public string FieldTypeFqn { get; }
        public string ParamName { get; }
        /// <summary>When non-null, the factory parameter is typed as this and the body emits an explicit cast.</summary>
        public string ParamTypeOverride { get; }
        public string ParamTypeFqn => ParamTypeOverride ?? FieldTypeFqn;
        public bool NeedsCast => ParamTypeOverride != null;
    }
}
