### YamlMime:ManagedReference

apiRules:
- exclude:
    hasAttribute:
      uid: Typhon.Engine.ExcludeDocFxAttribute
- include:
    type: Type
- include:
    type: Method
- include:
    type: Event
- include:
    type: Property
