import type { Config } from 'tailwindcss';

// Dark-first theming with `class="dark"` on <html>. Compact density is the only tier Phase 0 ships — token names are positioned
// so future density tiers (Regular, Roomy) would be a CSS-variable swap (`--density-*`) rather than a refactor of every utility.
// shadcn's slate base is referenced via CSS variables set in src/globals.css; this config only declares the variable bindings so
// Tailwind utilities like `bg-background`, `text-foreground`, `border-border` resolve. Tailwind v4's CSS-first config via
// `@theme` in globals.css is the primary config surface; this file exists mainly to tell the Tailwind language server and IDE
// tooling about the content scan path — v4 otherwise detects sources automatically.
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: 'var(--color-background)',
        foreground: 'var(--color-foreground)',
        border: 'var(--color-border)',
        muted: 'var(--color-muted)',
        'muted-foreground': 'var(--color-muted-foreground)',
      },
      spacing: {
        'density-1': 'var(--density-spacing-1)',
        'density-2': 'var(--density-spacing-2)',
        'density-3': 'var(--density-spacing-3)',
      },
      // fontSize utilities for density-sm / density-base are now generated by Tailwind v4 from
      // --text-density-* tokens declared in globals.css (@theme inline). No config needed here.
    },
  },
} satisfies Config;
