name: Typhon Regression Benchmark
on:
  push:
    branches:
      - master
      - dev

permissions:
  contents: write
  deployments: write
  issues: write
  pull-requests: write
  
jobs:
  benchmark:
    name: Run Benchmark.Net
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Run benchmark
        run: cd test/Typhon.Benchmark && dotnet run --configuration Release --exporters json --filter '*'

      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          name: Typhon Benchmark
          tool: 'benchmarkdotnet'
          output-file-path: test/Typhon.Benchmark/BenchmarkDotNet.Artifacts/results/Combined.Benchmarks.json
          benchmark-data-dir-path: bench
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '130%'
          comment-on-alert: true
          summary-always: true
          fail-on-alert: false
          alert-comment-cc-users: '@nockawa'